apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eshop-ingress
  namespace: flux-apps
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: eshop.local     # ðŸ‘ˆ or your DNS name / external IP
      http:
        paths:
          - path: /basket
            pathType: Prefix
            backend:
              service:
                name: basketapi-dev-app-svc
                port:
                  number: 80

          - path: /catalog
            pathType: Prefix
            backend:
              service:
                name: catelogapi-dev-app-svc
                port:
                  number: 80

          - path: /discount
            pathType: Prefix
            backend:
              service:
                name: discountapi-dev-app-svc
                port:
                  number: 80
