apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-stack
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/monitoring
  prune: true
  targetNamespace: monitoring  # âœ… ensures everything goes under monitoring
  dependsOn:
    - name: flux-infra