apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: flux-infra
  namespace: flux-system
spec:
  interval: 5m
  path: ../../infrastructure
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: flux-apps
  dependsOn:
    - name: flux-apps