releaseName: basketapi-dev
configMapName: basketapi-dev-config
secretName: basketapi-dev-secret

replicaCount: 1

image:
  repository: eshopmicroserviceacr.azurecr.io/basketapi
  tag: "937"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  containerPort: 8080

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: false

serviceAccount:
  create: true

config:
  ASPNETCORE_ENVIRONMENT: "Development"
  ASPNETCORE_URLS: "http://+:8080"
  ConnectionStrings__DatabaseHost: "eshopmicroservicepostgres.postgres.database.azure.com"
  ConnectionStrings__DatabasePort: "5432"
  ConnectionStrings__DatabaseUser: "postgres"
  ConnectionStrings__DatabaseName: "BasketDB"
  ConnectionStrings__DatabaseSslMode: "allow"
  ConnectionStrings__Redis: "distributedcache:6379"
  MessageBrocker__Host: "amqp://ecommerce-mq:5672"
  MessageBrocker__UserName: "guest"
  AuthAD__Authority: "https://duedendidentityserver:8081"

secret:
  MessageBrocker__Password: "guest"
  DatabasePassword: "postgres123"
