apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - helm-repository.yaml
  - helm-release.yaml
  - configmap-dashboard.yaml

# âœ… This will override the invalid labels
commonMetadata:
  labels:
    app.kubernetes.io/managed-by: kustomize