apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-ingressgateway
  namespace: flux-system
spec:
  chart:
    spec:
      chart: gateway
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
      version: "1.22.0"
  interval: 5m
  dependsOn:
    - name: istio-base
    - name: istiod
  values:
    service:
      type: LoadBalancer