apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - helm-repository.yaml
  - helm-release-istio-base.yaml
  - helm-release-istiod.yaml
  - helm-release-istio-ingressgateway.yaml
