releaseName: discountapi-dev

replicaCount: 1

image:
  repository: eshopmicroserviceacr.azurecr.io/discountapi
  tag: "1329"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  containerPort: 8080

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: false

# autoscaling:
#   enabled: true
#   minReplicas: 1
#   maxReplicas: 5
#   targetCPUUtilizationPercentage: 80

# serviceAccount:
#   create: true
#   annotations:
#     azure.workload.identity/client-id: "d5600dfe-0f09-4a9c-8e38-65d67a71f106"  # Add your Azure Managed Identity
#     azure.workload.identity/tenant-id: "16a2d9b2-56e7-4050-878d-9be9618dcb9f"
#   name: "discountapi-dev"

serviceAccount:
  create: false
  name: ""

envFrom:
  configMap: discountapi-dev-config

config:
  ASPNETCORE_ENVIRONMENT: "Development"
  ASPNETCORE_URLS: "http://+:8080"
