apiVersion: v1
kind: ConfigMap
metadata:
  name: catelogapi-config
data:
  ASPNETCORE_ENVIRONMENT: Development
  ConnectionStrings__Database: "Server=catelogdb;Port=5432;User Id=postgres;Password=postgres123;Database=catelogDB;"
  GrpcSetting__DiscountUrl: "https://discountapi:8080"
  MessageBrocker__Host: "amqp://ecommerce-mq:5672"
  MessageBrocker__UserName: "guest"
  MessageBrocker__Password: "guest"
  AuthAD__Authority: "https://dudeserver:8081"
