apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-ingress
  namespace: istio-system
spec:
  interval: 10m
  releaseName: istio-ingress
  chart:
    spec:
      chart: gateway
      version: "1.21.0"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  dependsOn:
    - name: istio-base
      kind: HelmRelease
    - name: istiod
      kind: HelmRelease
  values:
    gateway:
      enabled: true
    global:
      istioNamespace: istio-system
    service:
      type: LoadBalancer
      # annotations for Azure LB (example)
      annotations:
        service.beta.kubernetes.io/azure-load-balancer-internal: "false"
