apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - helmrepository.yaml
  - ../../apps/nginx/dev/
  - ../../apps/basket/dev/
  - ../../apps/catelog/dev/
  - ../../apps/discount/dev/
