apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: monitoring-ingress-direct
  namespace: flux-system
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    # Skip validation webhook during bootstrap
    admissionregistration.k8s.io/v1: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: 4.220.25.50.nip.io
      http:
        paths:
          - path: /grafana(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: grafana
                port:
                  number: 80
          
          - path: /prometheus(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: prometheus-kube-prometheus-prometheus
                port:
                  number: 9090
          
          - path: /kibana(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: kibana-kibana
                port:
                  number: 
          
          - path: /elasticsearch(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: elasticsearch-master
                port:
                  number: 9200
          
          - path: /zipkin(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: zipkin
                port:
                  number: 9411
          
          - path: /jaeger(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: jaeger-query
                port:
                  number: 16686