apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - helm-repository.yaml
  - helm-release.yaml
  - ../logging/ingress.yaml
  - ../monitoring/ingress.yaml
  - ../tracing/ingress.yaml
  